import {
  TextIcon,
  TextBlockIcon,
  HashtagIcon,
  PhoneIcon,
  EmailIcon,
  HideIcon,
  CalendarIcon,
  AttachmentIcon,
  ColorIcon,
  ToggleOnIcon,
  MenuHorizontalIcon,
  SelectIcon,
  StatusActiveIcon,
  CheckboxIcon,
  ButtonIcon,
  ImageIcon,
  TextFontIcon,
  LinkIcon,
  TextTitleIcon,
  MinusIcon,
  ViewportTallIcon,
  TextQuoteIcon,
  CodeIcon,
  LayoutPopupIcon,
  MeasurementSizeIcon,
  FolderIcon,
} from "@shopify/polaris-icons";

export const defaultInputTypes = [
  { content: "Text", icon: TextIcon, disabled: false },
  { content: "Textarea", icon: TextBlockIcon, disabled: false },
  { content: "Number", icon: HashtagIcon, disabled: false },
  { content: "Phone", icon: PhoneIcon, disabled: true },
  { content: "Email", icon: EmailIcon, disabled: true },
  { content: "Hidden Field", icon: HideIcon, disabled: true },
  { content: "Datetime", icon: CalendarIcon, disabled: true },
  { content: "File Upload", icon: AttachmentIcon, disabled: true },
  { content: "Color Picker", icon: ColorIcon, disabled: true },
  { content: "Switch", icon: ToggleOnIcon, disabled: true },
  { content: "Range Slider", icon: MenuHorizontalIcon, disabled: true },
];

export const defaultSelectionTypes = [
  { content: "Select", icon: SelectIcon, disabled: false },
  { content: "Dropdown", icon: SelectIcon, disabled: false },
  { content: "Color Dropdown", icon: SelectIcon, disabled: true },
  { content: "Image Dropdown", icon: SelectIcon, disabled: true },
  { content: "Radio Button", icon: StatusActiveIcon, disabled: false },
  { content: "Checkbox", icon: CheckboxIcon, disabled: false },
  { content: "Button", icon: ButtonIcon, disabled: false },
  { content: "Color Swatch", icon: ColorIcon, disabled: false },
  { content: "Image Swatch", icon: ImageIcon, disabled: false },
  { content: "Font Picker", icon: TextFontIcon, disabled: true },
  { content: "Product Links", icon: LinkIcon, disabled: true },
];

export const defaultStaticTypes = [
  { content: "Heading", icon: TextTitleIcon, disabled: false },
  { content: "Divider", icon: MinusIcon, disabled: false },
  { content: "Spacing", icon: ViewportTallIcon, disabled: false },
  { content: "Paragraph", icon: TextQuoteIcon, disabled: false },
  { content: "HTML", icon: CodeIcon, disabled: true },
  { content: "Pop-up Modal", icon: LayoutPopupIcon, disabled: true },
  { content: "Size chart", icon: MeasurementSizeIcon, disabled: true },
  { content: "Tabs", icon: FolderIcon, disabled: true },
];
